/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rovernavigator;

import java.awt.Color;
import java.text.DecimalFormat;

/**
 *
 * @author Brian
 */
public class PanelResults extends javax.swing.JPanel {

    RoverNavigator main;
    
    /**
     * Creates new form PanelResults
     */
    public PanelResults() {
        initComponents();
    }
    
    public void setMain(RoverNavigator main) {
        this.main = main;
        updateStatus();
    }    

    public void updateStatus() {
        DecimalFormat formatDistance = new DecimalFormat("0.000");
        DecimalFormat formatDegrees = new DecimalFormat("0.0");
        DecimalFormat formatInteger = new DecimalFormat("0");
        
        labelDistance.setText(formatDistance.format(main.motionPath.getTravelDistance()));
        labelDegrees.setText(formatDegrees.format(main.motionPath.getTravelDegrees()));
        labelExperimentError.setText(formatDistance.format(main.motionPath.getExperimentError()));
        
        labelAvgError.setText(formatDistance.format(main.motionPath.getExperimentAvgError()));
        labelPathScore.setText("Path Score = " + formatDistance.format(main.motionPath.getPathScore()));

        labelCommandCount.setText(formatInteger.format(main.commands.getCount()));
        
        if (main.motionPath.hazardIntersects > 0) {
            labelHazardCount.setForeground(Color.red);
            labelHazardCount.setText(formatInteger.format(main.motionPath.hazardIntersects));
        } else {
            labelHazardCount.setForeground(new Color(0x00,0xb0,0x00));
            labelHazardCount.setText("None");
        }
            
        String msg = "";
        msg += "<html>";
        msg += "<table>";
        
        msg += "<tr>";
        msg += "<td>";
        msg += "ID";
        msg += "</td>";
        msg += "<td>";
        msg += "Completed";
        msg += "</td>";
        msg += "<td>";
        msg += "Error (m)";
        msg += "</td>";
        msg += "</tr>";
        
        int e = 0;
        while (e < main.motionPath.experiments) {
            e++;
            msg += "<tr>";
            msg += "<td>";
            msg += main.motionPath.testResult[e].id;
            msg += "</td>";
            msg += "<td>";
            if (main.motionPath.testResult[e].completed) msg += "Yes";
            else msg += "No";
            msg += "</td>";
            msg += "<td>";
            msg += formatDistance.format(main.motionPath.testResult[e].distError);
            msg += "</td>";
            msg += "</tr>";
        }
        if (e == 0) {
            msg += "<tr>";
            msg += "<td>";
            msg += "No";
            msg += "</td>";
            msg += "<td>";
            msg += "Experiments";
            msg += "</td>";
            msg += "<td>";
            msg += "Found";
            msg += "</td>";
            msg += "</tr>";            
        }
        
        msg += "</table>";
        msg += "</html>";
        labelTestResults.setText(msg);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPathScore = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelAvgError = new javax.swing.JLabel();
        labelExperimentError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelDegrees = new javax.swing.JLabel();
        labelDistance = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        labelCommandCount = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelTestResults = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelHazardCount = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(120, 400));

        labelPathScore.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelPathScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPathScore.setText("Score 0.0");

        jLabel5.setText("Avg Error (m)");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 14));

        labelAvgError.setText("Error");
        labelAvgError.setPreferredSize(new java.awt.Dimension(60, 14));

        labelExperimentError.setText("Error");
        labelExperimentError.setPreferredSize(new java.awt.Dimension(60, 14));

        jLabel4.setText("Total Error (m)");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 14));

        jLabel3.setText("Total Degrees");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 14));

        labelDegrees.setText("Degrees");
        labelDegrees.setPreferredSize(new java.awt.Dimension(60, 14));

        labelDistance.setText("Distance");
        labelDistance.setPreferredSize(new java.awt.Dimension(60, 14));

        jLabel2.setText("Total Distance (m)");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 14));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCORING");

        jLabel6.setText("# of Commands");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 14));

        labelCommandCount.setText("Error");
        labelCommandCount.setPreferredSize(new java.awt.Dimension(60, 14));

        labelTestResults.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTestResults.setText("Experiment Results");
        labelTestResults.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Experiment Results");

        jLabel8.setLabelFor(labelHazardCount);
        jLabel8.setText("# of Hazard Hits");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 14));

        labelHazardCount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelHazardCount.setText("Error");
        labelHazardCount.setPreferredSize(new java.awt.Dimension(60, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
            .addComponent(labelPathScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addComponent(labelTestResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelAvgError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelHazardCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
                        .addComponent(labelCommandCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDegrees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelExperimentError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDegrees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelExperimentError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPathScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAvgError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCommandCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHazardCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addComponent(labelTestResults, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelAvgError;
    private javax.swing.JLabel labelCommandCount;
    public javax.swing.JLabel labelDegrees;
    public javax.swing.JLabel labelDistance;
    private javax.swing.JLabel labelExperimentError;
    private javax.swing.JLabel labelHazardCount;
    private javax.swing.JLabel labelPathScore;
    private javax.swing.JLabel labelTestResults;
    // End of variables declaration//GEN-END:variables
}
